---
# tasks file for hostname

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - hostname

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - hostname

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - hostname

- name: Configure hostname
  become: yes
  hostname:
    name: "{{ hostname_name }}"
  tags:
    - hostname
